apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocking-svc
  namespace: poc
  labels:
    app: blocking-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocking-svc
  template:
    metadata:
      labels:
        app: blocking-svc
    spec:
      containers:
      - image: docker.io/library/blocking-svc:0.0.1-SNAPSHOT
        name: blocking-svc
        ports:
        - containerPort: 8080
          name: http-port
        envFrom:
        - configMapRef:
            name: blocking-svc-cm-1
        volumeMounts:
          - name: spring-vol
            mountPath: /config
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: spring-vol
          configMap:
            name: blocking-svc-cm-2

---
## configmap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: poc
  name: blocking-svc-cm-1
data:
  SERVER_PORT: "8080"
  JAVAX_LOG_LEVEL: TRACE
  BPL_JVM_THREAD_COUNT: "50"
  BACKEND_SVC_URL: http://backend-svc:8080/backend/employees
  SPRING_CONFIG_LOCATION: /config/spring_additional_config.properties

---
## configmap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: poc
  name: blocking-svc-cm-2
data:
  spring_additional_config.properties: |-
    dummy.key=dummy.value

---
## blocking-svc

apiVersion: v1
kind: Service
metadata:
  namespace: poc
  name: blocking-svc
spec:
  selector:
    app: blocking-svc
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: http-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blocking-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: www.blocking.com
    http:
      paths:
      - path: /blocking
        pathType: Prefix
        backend:
          service:
            name: blocking-svc
            port:
              number: 8080